config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dashboard, only: :index
  resources :projects, except: [:index] do
    resources :tasks, except: [:index] do
      member do
        get 'get_task'
        get 'done_task'
      end
    end
  end
  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user, foreign_key: :owner, class_name: User
  has_many :tasks, dependent: :destroy

  validates :name, :description, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user, foreign_key: :owner, class_name: User

  validates :name, :text, presence: true

  scope :task_new, -> { where(status: 'new') }
  scope :progress, -> { where(status: 'progress') }
  scope :done,     -> { where(status: 'done') }

  enum priority: [ :low, :middle, :warning ]

  def to_work
    update_attribute(:status, 'progress')
  end

  def to_done
    update_attribute(:status, 'done')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects, foreign_key: :owner, class_name: Project, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @projects = current_user.projects.order(:created_at)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html, :xml
  before_action :get_resource, only: [:edit, :show, :update, :destroy]

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
    respond_to do |format|
      if @project.save
        flash[:notice] = "Project successfully created"
        format.html { redirect_to dashboard_index_path }
        format.js   { render :show }
      else
        flash[:error] = "What's wrong?"
        render :back
      end
    end
  end

  def edit
    render 'new'
  end

  def show
    @tasks_new = @project.tasks.task_new.order(priority: 'DESC')
    @progress = @project.tasks.progress.order(priority: 'DESC')
    @done = @project.tasks.done.order(priority: 'DESC')
  end

  def update
    @tasks_new = @project.tasks.task_new.order(priority: 'DESC')
    @progress = @project.tasks.progress.order(priority: 'DESC')
    @done = @project.tasks.done.order(priority: 'DESC')
    respond_to do |format|
      if @project.update(project_params)
        flash[:notice] = "Project successfully updated"
        format.html { redirect_to dashboard_index_path }
        format.js   { render :show }
      else
        flash[:error] = "What's wrong?"
        render :back
      end
    end
  end

  def destroy
    @project.delete
    flash[:notice] = "#{ @project.name } is was removed!"
    redirect_to dashboard_index_path
  end

  def get_resource
    @project = Project.find(params[:id])
  end

  private
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :xml
  before_action :get_resources, only: [:show, :edit, :update, :destroy, :get_task, :done_task]
  before_action :get_collections, only: [:destroy, :get_task, :done_task]

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build(task_params)
    if @task.save
      @tasks_new = @project.tasks.task_new.order(priority: 'DESC')
      @progress = @project.tasks.progress.order(priority: 'DESC')
      @done = @project.tasks.done
      flash[:notice] = "Project successfully created"
      render 'projects/show'
    else
      flash[:error] = "What's wrong?"
      render :back
    end
  end

  def show
  end

  def edit
    render 'new'
  end

  def update
    if @task.update(task_params)
      flash[:notice] = "Project successfully updated"
      render 'show'
    else
      flash[:error] = "What's wrong?"
      render :back
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = "#{ @task.name } is was removed!"
    render 'projects/show'
  end

  def get_task
    @task.to_work
    render 'projects/show'
  end

  def done_task
    @task.to_done
    render 'projects/show'
  end

  def get_resources
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
  end

  def get_collections
    @tasks_new = @project.tasks.task_new.order(priority: 'DESC')
    @progress = @project.tasks.progress.order(priority: 'DESC')
    @done = @project.tasks.done
  end

  private
    def task_params
      params.require(:task).permit(:name, :text, :priority, :deadline)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_footer.html.erb
<footer class="footer-2">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <a class="text-link" href="#">vitalikstetsenko@hotmail.com <i class="icon arrow_right"></i></a>
        <span class="copyright">© 2016 Vitalik Stetsenko</span>
      </div>
    </div>
  </div><!--end of container-->
</footer>

app/views/common/_header.html.erb
<div class="nav-container">
  <nav class="nav-1">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <ul class="menu">
            <a href="/" class="home-link">
              <%= image_tag('tm-logo.png', class: "logo" ) %>
            </a>
            <% unless request[:controller] == 'home' %>
              <li><%= link_to "Dashboard", dashboard_index_path %></li>
              <% if request[:controller] == 'dashboard' %>
                <li><%= link_to 'New Project', new_project_path, remote: true %></li>
              <% elsif request[:controller] == 'projects' && request[:action] == 'show' %>
                <li><%= link_to "Edit Project", edit_project_path(@project), remote: true  %></li>
                <li><%= link_to "Remove Project", project_path(@project), method: :delete,
                                            data: { confirm: "Are you sure you want to delete PROJECT: '#{@project.name}'?" } %></li>
                <li><%= link_to "New Task", new_project_task_path(@project), remote: true  %></li>
              <% elsif request[:controller] == 'projects' && request[:action] == 'create' %>
                <li><%= link_to "Edit Project", edit_project_path(@project), remote: true  %></li>
                <li><%= link_to "Remove Project", project_path(@project), method: :delete,
                                            data: { confirm: "Are you sure you want to delete PROJECT: '#{@project.name}'?" } %></li>
                <li><%= link_to "New Task", new_project_task_path(@project), remote: true  %></li>
              <% elsif request[:controller] == 'projects' && request[:action] == 'update' %>
                <li><%= link_to "Edit Project", edit_project_path(@project), remote: true  %></li>
                <li><%= link_to "Remove Project", project_path(@project), method: :delete,
                                            data: { confirm: "Are you sure you want to delete PROJECT: '#{@project.name}'?" } %></li>
                <li><%= link_to "New Task", new_project_task_path(@project), remote: true  %></li>
              <% elsif request[:controller] == 'tasks' && request[:action] == 'show' %>
                <li><%= link_to "Current Project", project_path(@project), remote: true  %></li>
                <li><%= link_to "Edit Task", edit_project_task_path(@project, @task), remote: true  %></li>
                <li><%= link_to "Remove Task", project_task_path(@project, @task), method: :delete,
                                            data: { confirm: "Are you sure you want to delete TASK: '#{@task.name}'?" }, remote: true %></li>
              <% elsif request[:controller] == 'tasks' && request[:action] == 'create' %>
                <li><%= link_to "Edit Project", edit_project_path(@project), remote: true  %></li>
                <li><%= link_to "Remove Project", project_path(@project), method: :delete,
                                            data: { confirm: "Are you sure you want to delete PROJECT: '#{@project.name}'?" } %></li>
                <li><%= link_to "New Task", new_project_task_path(@project), remote: true  %></li>
              <% elsif request[:controller] == 'tasks' && request[:action] == 'update' %>
                <li><%= link_to "Current Project", project_path(@project), remote: true  %></li>
                <li><%= link_to "Edit Task", edit_project_task_path(@project, @task), remote: true  %></li>
                <li><%= link_to "Remove Task", project_task_path(@project, @task), method: :delete,
                                            data: { confirm: "Are you sure you want to delete TASK: '#{@task.name}'?" }, remote: true %></li>
              <% elsif request[:controller] == 'tasks' && request[:action] == 'destroy' %>
                <li><%= link_to "Edit Project", edit_project_path(@project), remote: true  %></li>
                <li><%= link_to "Remove Project", project_path(@project), method: :delete,
                                            data: { confirm: "Are you sure you want to delete PROJECT: '#{@project.name}'?" } %></li>
                <li><%= link_to "New Task", new_project_task_path(@project), remote: true  %></li>
              <% elsif request[:controller] == 'tasks' && request[:action] == 'get_task' %>
                <li><%= link_to "Edit Project", edit_project_path(@project), remote: true  %></li>
                <li><%= link_to "Remove Project", project_path(@project), method: :delete,
                                            data: { confirm: "Are you sure you want to delete PROJECT: '#{@project.name}'?" } %></li>
                <li><%= link_to "New Task", new_project_task_path(@project), remote: true  %></li>
                <% elsif request[:controller] == 'tasks' && request[:action] == 'done_task' %>
                <li><%= link_to "Edit Project", edit_project_path(@project), remote: true  %></li>
                <li><%= link_to "Remove Project", project_path(@project), method: :delete,
                                            data: { confirm: "Are you sure you want to delete PROJECT: '#{@project.name}'?" } %></li>
                <li><%= link_to "New Task", new_project_task_path(@project), remote: true  %></li>
              <% end %>
            <% end %>
          </ul>
          <ul class="social-links">
            <% if current_user %>
              <li style="color:#e74c3c"><b><%= current_user.email %></b></li>
              <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div><!--end of row-->
    </div><!--end of container-->
  </nav>
</div>

app/views/dashboard/index.html.erb
<div id='all'>
  <%= render 'common/header' %>
  <div class="main-container" id='main-projects'>
    <section class="page-header short">
      <div class="background-image-holder overlay">
        <%= image_tag('body1.jpg', alt: "Slide Background", class: "background-image") %>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <h1 class='text-center'>Projects</h1>
          </div>
        </div>
      </div>
    </section>
    <section class="products-1">
      <div class="container">
        <div class="row">
          <% if @projects.present? %>
            <% @projects.each do |project| %>
              <div class="col-md-4 col-sm-6">
                <div class="product">
                  <h5><%= link_to "#{ project.name }", project, remote: true %></h5><br>
                  <%= truncate("#{ project.description }", length: 100) %>
                </div>
              </div>
            <% end %>
          <% else %>
            <h5 class='text-center'><%= 'Create your first project' %></h5>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>TasksManager</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/project/_new.html.erb
<div class="main-container">
  <section class="contained-projects">
    <div class="col-sm-8 col-sm-offset-2">
      <h3 class='text-center'>New Project</h3>
      <%= form_for :project, url: project_index_path, html: { role: 'form', "data-toggle" => "validator" } do |p| %>
        <div class="form-md-line-input">
          <div class="form-group">
            <%= hidden_field_tag 'project[owner]', @owner.id %>
            <%= p.text_field :name, class: "form-control", placeholder: "Enter project name", "data-error"=>"Must not be empty", required: true %>
            <%= p.text_area :description, class: "form-control", placeholder: "Enter project description", rows: '6', "data-error"=>"Must not be empty", required: true %>
          </div>
          <div class="col-sm-1 col-sm-offset-3 form-group">
            <%= p.submit "Create", class: "btn btn-default", type: "submit" %>
          </div>
        </div>
      <% end %>
      <div class="col-sm-offset-3 text-center form-group">
        <%= link_to "Cansel", dashboard_index_path, class: "btn btn-default" %>
      </div>
    </div>
  </section>
</div>

app/views/projects/_form.html.erb
<div id="all">
  <%= render 'common/header' %>
  <div class="main-container">
    <section class="contained-projects">
      <div class="col-sm-8 col-sm-offset-2">
        <% if request[:action] == 'edit' %>
          <h3 class='text-center'>Edit Project</h3>
        <% else %>
          <h3 class='text-center'>New Project</h3>
        <% end %>
        <%= form_for(@project, remote: true) do |p| %>
          <div class="form-md-line-input">
            <div class="form-group">
              <%= p.text_field :name, class: "form-control", placeholder: "Enter project name", required: true %>
              <%= p.text_area :description, class: "form-control", placeholder: "Enter project description", rows: '6', required: true %>
            </div>
            <div class="col-sm-1 col-sm-offset-3 form-group">
              <% if request[:action] == 'new' %>
                <%= p.submit "Create", class: "btn btn-default", type: "submit" %>
              <% else request[:action] == 'edit' %>
                <%= p.submit "Update", class: "btn btn-default", type: "submit" %>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="col-sm-offset-3 text-center form-group">
          <% if request[:action] == 'new' %>
            <%= link_to "Cancel", dashboard_index_path, class: "btn btn-default" %>
          <% else request[:action] == 'edit' %>
            <%= link_to "Cancel", @project, class: "btn btn-default", remote: true %>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/projects/_new.html.erb
<div id="all">
  <%= render 'common/header' %>
  <div class="main-container">
    <section class="contained-projects">
      <div class="col-sm-8 col-sm-offset-2">
        <% if request[:action] == 'edit' %>
          <h3 class='text-center'>Edit Project</h3>
        <% else %>
          <h3 class='text-center'>New Project</h3>
        <% end %>
        <%= form_for(@project, remote: true) do |p| %>
          <div class="form-md-line-input">
            <div class="form-group">
              <%= p.text_field :name, class: "form-control", placeholder: "Enter project name", required: true %>
              <%= p.text_area :description, class: "form-control", placeholder: "Enter project description", rows: '6', required: true %>
            </div>
            <div class="col-sm-1 col-sm-offset-3 form-group">
              <% if request[:action] == 'new' %>
                <%= p.submit "Create", class: "btn btn-default", type: "submit" %>
              <% else request[:action] == 'edit' %>
                <%= p.submit "Update", class: "btn btn-default", type: "submit" %>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="col-sm-offset-3 text-center form-group">
          <% if request[:action] == 'new' %>
            <%= link_to "Cansel", dashboard_index_path, class: "btn btn-default" %>
          <% else request[:action] == 'edit' %>
            <%= link_to "Cansel", @project, class: "btn btn-default", remote: true %>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/projects/_show.html.erb
<div id="all">
  <%= render 'common/header' %>
  <div class="main-container">
    <section class="contained-projects">
      <div class="col-sm-8 col-sm-offset-2">
        <h3><%= "#{ @project.name }" %></h3>
        <%= "#{ @project.description }" %>
      </div>
    </section>
    <div class="container">
      <div class="row">
        <div class="product-container">
          <hr>
          <div class="col-md-4 col-sm-6 text-center">
            <h3 class="text-center">New tasks</h3>
            <% if @tasks_new.present? %>
              <% @tasks_new.each do |task| %>
                <div class="product">
                  <h5><%= link_to "#{ task.name }", project_task_path(task, project_id: @project), remote: true %></h5><br>
                  <% if task.priority == 'low' %>
                    <div style="color:green">
                  <% elsif task.priority == 'middle' %>
                    <div style="color:orange">
                  <% else %>
                    <div style="color:red">
                  <% end %>
                    <%= "#{ task.priority } priority" %><br>
                  </div>
                  <% if task.deadline.present? %>
                    <span><%= "Deadline: #{ task.deadline }" %></span>
                  <% end %>
                  <ul><%= "#{ task.text }" %></ul>
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-4 col-sm-6 text-center">
            <h3 class="text-center">Progress</h3>
            <% if @progress.present? %>
              <% @progress.each do |task| %>
                <div class="product">
                  <h5><%= link_to "#{ task.name }", project_task_path(task, project_id: @project), remote: true %></h5><br>
                  <% if task.priority == 'low' %>
                    <div style="color:green">
                  <% elsif task.priority == 'middle' %>
                    <div style="color:orange">
                  <% else %>
                    <div style="color:red">
                  <% end %>
                    <%= "#{ task.priority } priority" %><br>
                  </div>
                  <% if task.deadline.present? %>
                    <span><%= "Deadline: #{ task.deadline }" %></span>
                  <% end %>
                  <ul><%= "#{ task.text }" %></ul>
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-4 col-sm-6 text-center">
            <h3 class="text-center">Done</h3>
            <% if @done.present? %>
              <% @done.each do |task| %>
                <div class="product">
                  <h5><%= link_to "#{ task.name }", project_task_path(task, project_id: @project), remote: true %></h5><br>
                  <% if task.priority == 'low' %>
                    <div style="color:green">
                  <% elsif task.priority == 'middle' %>
                    <div style="color:orange">
                  <% else %>
                    <div style="color:red">
                  <% end %>
                    <%= "#{ task.priority } priority" %><br>
                  </div>
                  <% if task.deadline.present? %>
                    <span><%= "Deadline: #{ task.deadline }" %></span>
                  <% end %>
                  <ul><%= "#{ task.text }" %></ul>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.js.erb
$('#all').replaceWith("<%= j ( render 'new.html.erb' ) %>")

app/views/projects/show.js.erb
$('#all').replaceWith("<%= j ( render 'projects/show.html.erb' ) %>")

app/views/tasks/_form.html.erb
<div id="all">
  <%= render 'common/header' %>
  <div class="main-container">
    <section class="contained-projects">
      <div class="col-sm-8 col-sm-offset-2">
        <% if request[:action] == 'edit' %>
          <h3 class='text-center'>Edit Task</h3>
        <% else %>
          <h3 class='text-center'>New Task</h3>
        <% end %>
        <%= form_for([@project, @task], remote: true) do |p| %>
          <div class="form-md-line-input" id="sandbox-container">
            <div class="form-group">
              <%= p.text_field :name, class: "form-control", placeholder: "Enter task name", required: true %>
              <%= p.text_area :text, class: "form-control", placeholder: "Enter task text", rows: '10', required: true %>
              <%= p.label :priority %>
              <%= p.select(:priority, options_for_select(['low', 'middle', 'warning']), {}, { class: "form-control", placeholder: "Select priority..." }) %>
              <%= p.text_field :deadline, 'data-provide' => 'datepicker', class: "form-control", placeholder: 'Select deadline...' %>
            </div>
            <div class="col-sm-1 col-sm-offset-3 form-group">
              <% if request[:action] == 'new' %>
                <%= p.submit "Create", class: "btn btn-default", type: "submit" %>
              <% else request[:action] == 'edit' %>
                <%= p.submit "Update", class: "btn btn-default", type: "submit" %>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="col-sm-offset-3 text-center form-group">
          <%= link_to "Cancel", @project, class: "btn btn-default", remote: true %>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/tasks/_show.html.erb
<div id="all">
  <%= render 'common/header' %>
  <div class="main-container">
    <section class="contained-projects">
      <div class="col-sm-8 col-sm-offset-2">
        <h2><%= "#{ @task.name }" %></h2>
        <% if @task.priority == 'low' %>
          <div style="color:green">
        <% elsif @task.priority == 'middle' %>
          <div style="color:orange">
        <% else %>
          <div style="color:red">
        <% end %>
          <%= "#{ @task.priority } priority" %><br>
        </div>
        <ul style="color:#e74c3c"><%= "Deadline: #{ @task.deadline }" if @task.deadline.present? %></ul><br>
        <span><%= "#{ @task.text }" %></span>
      </div>
    </section>
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-center">
          <br>
          <% if @task.status == 'new' || @task.status == 'done' %>
            <%= link_to 'Get Task to work', get_task_project_task_path(@project, @task), class: 'bnt btn-sm', remote: true %>
          <% else %>
            <%= link_to 'Done', done_task_project_task_path(@project, @task), class: 'bnt btn-sm', remote: true %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.js.erb
$('#all').replaceWith("<%= j ( render 'form.html.erb' ) %>")

app/views/tasks/show.js.erb
$('#all').replaceWith("<%= j ( render 'show.html.erb' ) %>")